---
- name: Certificate| Copy CA certs to target hosts
  become: true
  ansible.builtin.copy:
    src:  "{{ linuxSoePath }}/soe/cert/" 
    dest: /etc/pki/ca-trust/source/anchors/
    remote_src: yes
  ignore_errors: True

- name: Certificate| Update CA trust store
  shell: "update-ca-trust"
  become: true
  ignore_errors: True
