---
- name: Certificate| Install a list of packages
  become: true
  ansible.builtin.apt:
    pkg:
    - ca-certificates
    state: present
  ignore_errors: True

- name: Certificate| Copy CA certs to target hosts
  become: true
  ansible.builtin.copy:
    src:  "{{ linuxSoePath }}/soe/cert/" 
    dest: /usr/local/share/ca-certificates/
    remote_src: yes
  ignore_errors: True

- name: Certificate| Update CA trust store
  shell: "update-ca-certificates"
  become: true
  ignore_errors: True
