---
- name: Crowdstrike| gather secrets
  include_tasks: get_kv_secrets.yml
  vars:
    secretName: "oricacscid"
  register: kvValue
  ignore_errors: True

- name: Crowdstrike| declare falcon cid
  ansible.builtin.set_fact:
    oricacscid: "{{ kvValue }}"
  ignore_errors: True

- name: Crowdstrike| install rpm package
  become: true
  ansible.builtin.dnf: 
    name: "{{ linuxSoePath }}/soe/linux/rpm/falcon-sensor-7.el{{ ansible_distribution_major_version }}.x86_64.rpm"
    state: present
    disable_gpg_check: true
  ignore_errors: True

- name: Crowdstrike| configure CID
  become: true
  shell: "/opt/CrowdStrike/falconctl -s -f --cid={{ oricacscid }}"
  when: ansible_facts['services']['falcon-sensor.service']['state']| default('not-found') == 'not-found'
  ignore_errors: True

- name: Crowdstrike| enable and start falcon-sensor
  become: true
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: falcon-sensor
  when: ansible_facts['services']['falcon-sensor.service']['state']| default('not-found') != 'running'
  ignore_errors: True
