---
- name: Populate service facts
  ansible.builtin.service_facts:
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto
- name: Classify hosts depending on their OS distribution
  group_by:
    key: os_{{ ansible_facts['distribution'] }}
- name: download azcopy
  become: true
  ansible.builtin.get_url:
    url:  "{{ azcopyUrl }}" 
    dest: "/usr/bin/azcopy"
    mode: "0755"
- name: linuxSoeUri| gather secrets
  include_tasks: get_kv_secrets.yml
  vars:
    secretName: "linuxSoeUri"
  register: kvValue
- name: linuxSoeUri| declare
  ansible.builtin.set_fact:
    linuxSoeUri: kvValue 
- name: SOEfiles| download soe files via azcopy
  become: true
  ansible.builtin.shell: /usr/bin/azcopy copy --recursive --overwrite false linuxSoeUri  linuxSoePath 

- name: SSH| Copy banner from soe directory
  become: true
  ansible.builtin.copy:
    src:  "{{ linuxSoePath }}/soe/linux/banner.txt" 
    dest: /etc/ssh/banner.txt
    remote_src: yes
- name: SSH| Configure sshd_config with banner and PermitRootLogin
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#Banner none'
    line: 'Banner /etc/ssh/banner.txt'
- name: SSH| Configure sshd_config with banner and PermitRootLogin
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#PermitRootLogin prohibit-password'
    line: 'PermitRootLogin no'
- name: SSH| enable and start sshd
  become: true
  ansible.builtin.systemd_service:
    state: restarted
    name: sshd

- name: Certificate| install
  include_tasks: certificate-{{ ansible_facts['os_family']|lower }}.yml

- name: DNS| add suffix
  include_tasks: dnssuffix-{{ ansible_facts['os_family']|lower }}.yml

- name: ServiceNowAgent| install 
  include_tasks: servicenowagent-{{ ansible_facts['os_family']|lower }}.yml
  when: install_servicenowagent | bool or install_servicenowagent is undefined

- name: Crowdstrike| install 
  include_tasks: crowdstrike-{{ ansible_facts['os_family']|lower }}.yml
  when: install_crowdstrike | bool or install_crowdstrike is undefined

- name: Qualys| install 
  include_tasks: qualys-{{ ansible_facts['os_family']|lower }}.yml
  when: install_qualys | bool or install_qualys is undefined

- name: ServiceNowAcc| install 
  include_tasks: servicenowacc-{{ ansible_facts['os_family']|lower }}.yml
  when: install_servicenowacc | bool or install_servicenowacc is undefined
  
- name: Nxlog| install 
  include_tasks: nxlog-{{ ansible_facts['os_family']|lower }}.yml
  when: install_nxlog | bool or install_nxlog is undefined

- name: Illumio| install 
  include_tasks: illumio.yml
  when: install_illumio | bool or install_illumio is undefined

- name: Icinga| Allow 
  include_tasks: icinga-{{ ansible_facts['os_family']|lower }}.yml
  when: install_icinga | bool or install_icinga is undefined

- name: Join Ori Domain 
  include_tasks: joinoridomain-{{ ansible_facts['os_family']|lower }}.yml
  when: joinOriDomain | bool
