---
#install and configure nxlog / point to 10.172.32.101
- name: Nxlog| Install a list of packages
  become: true
  ansible.builtin.dnf:
    pkg:
    - apr
    - libdbi1
    state: present
- name: Nxlog| install deb package
  become: true
  ansible.builtin.dnf: 
    deb: "{{ linuxSoePath }}/soe/linux/deb/nxlog-ce-3.2.2329_rhel{{ ansible_distribution_major_version }}.x86_64.rpm"
#config goes here