---
#install and configure nxlog / point to 10.172.32.101
- name: Nxlog| Install a list of packages
  become: true
  ansible.builtin.dnf:
    pkg:
    - apr
    - perl-libs
    state: present
- name: Nxlog| install package
  become: true
  ansible.builtin.dnf: 
    name: "{{ linuxSoePath }}/soe/linux/rpm/nxlog-ce-3.2.2329_rhel{{ ansible_distribution_major_version }}.x86_64.rpm"
    disable_gpg_check: true
#config goes here