---
- name: Qualys| gather secrets (qualysCid)
  include_tasks: get_kv_secrets.yml
  vars:
    secretName: "qualysCid"
  register: kvValue
  ignore_errors: True

- name: Qualys| declare qualysCid 
  ansible.builtin.set_fact:
    qualysCid: "{{ kvValue }}"
  ignore_errors: True

- name: Qualys| gather secrets (qualysActId)
  include_tasks: get_kv_secrets.yml
  vars:
    secretName: "qualysActId"
  register: kvValue
  ignore_errors: True

- name: Qualys| declare qualysActId 
  ansible.builtin.set_fact:
    qualysActId: "{{ kvValue }}"
  ignore_errors: True

- name: Qualys| gather secrets (qualysUri)
  include_tasks: get_kv_secrets.yml
  vars:
    secretName: "qualysUri"
  register: kvValue
  ignore_errors: True

- name: Qualys| declare qualysUri 
  ansible.builtin.set_fact:
    qualysUri: "{{ kvValue }}"
  ignore_errors: True

- name: Qualys| install package
  become: true
  ansible.builtin.dnf: 
    name: "{{ linuxSoePath }}/linuxsoe/rpm/QualysCloudAgent.rpm"
    disable_gpg_check: true
  when: "'qualys-cloud-agent' not in ansible_facts.packages"
  ignore_errors: True

- name: Qualys| configure CID
  become: true
  shell: "/usr/local/qualys/cloud-agent/bin/qualys-cloud-agent.sh CustomerId={{ qualysCid }} ActivationId={{ qualysActId }} ServerUri={{ qualysUri }}"
  when: ansible_facts['services']['qualys-cloud-agent.service']['state']| default('not-found')!='running'
  ignore_errors: True

- name: Qualys| enable and start service
  become: true
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: qualys-cloud-agent
  when: ansible_facts['services']['qualys-cloud-agent.service']['state']| default('not-found') != 'running'
  ignore_errors: True
