---
#install servicenow agent
- name: ServiceNowAgent: install deb package
  become: true
  ansible.builtin.apt: 
    deb: "{{ linuxSoePath }}/soe/linux/deb/Orica-Linux-snowagent-7.0.0-x64.deb"
- name: ServiceNowAgent: update configuration
  shell: "/opt/snow/snowcron -f /opt/snow/snowcron.conf /opt/snow/snowagent"
  become: true