---
#install servicenow agent
- name: ServiceNowAgent|install package
  become: true
  ansible.builtin.dnf: 
    name: "{{ linuxSoePath }}/linuxsoe/rpm/Orica-Linux-snowagent-7.0.0-x64.rpm"
    state: present
    disable_gpg_check: true
  ignore_errors: True

- name: ServiceNowAgent|update configuration
  shell: "/opt/snow/snowcron -f /opt/snow/snowcron.conf /opt/snow/snowagent"
  become: true
  ignore_errors: True
