---
- name: Subscription| gather secrets rhel-actid
  include_tasks: get_kv_secrets.yml
  vars:
    secretName: "rhel-actid"
  register: kvValue
  ignore_errors: True


- name:  Subscription| declare rhel-actid
  ansible.builtin.set_fact:
    rhel_actid: "{{ kvValue }}"
  ignore_errors: True

- name: Subscription| gather secrets rhel-orgid
  include_tasks: get_kv_secrets.yml
  vars:
    secretName: "rhel-orgid"
  register: kvValue
  ignore_errors: True

- name:  Subscription| declare rhel-actid
  ansible.builtin.set_fact:
    rhel_orgid: "{{ kvValue }}"
  ignore_errors: True

- name: Subscription| Register and subscribe
  become: true
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ rhel_actid }}"
    org_id: "{{ rhel_orgid }}"
  ignore_errors: True
