---
- name: Subscription| gather secrets rhel-actid
  include_tasks: get_kv_secrets.yml
  vars:
    secretName: "rhel-actid"
  register: kvValue

- name:  Subscription|  declare rhel-actid
  ansible.builtin.set_fact:
    rhel_actid: "{{ kvValue }}"

- name: Subscription| gather secrets rhel-orgid
  include_tasks: get_kv_secrets.yml
  vars:
    secretName: "rhel-orgid"
  register: kvValue

- name:  Subscription|  declare rhel-actid
  ansible.builtin.set_fact:
    rhel_orgid: "{{ kvValue }}"

- name: Register and subscribe to multiple pools.
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ rhel_actid }}"
    org_id: "{{ rhel_orgid }}"
