---

 - name: talk to all hosts just so we can learn about them
   hosts: localhost
   gather_facts: no
   tasks:
     - name: gather secrets (linuxSoeUri)
       include_tasks: get_kv_secrets.yml
       vars:
         secretName: "linuxSoeUri"
       register: linuxSoeUri
     - name: gather secrets (falcon)
       include_tasks: get_kv_secrets.yml
       vars:
         secretName: "oricacscid"
       register: oricacscid
     - debug:
        msg: linuxSoeUri is {{ linuxSoeUri }}
 - name: talk to all hosts just so we can learn about them
   hosts: dev
   gather_facts: yes
   vars:
     linuxSoeUri: "{{ hostvars['localhost']['linuxSoeUri'] }}"
     oricacscid: "{{ hostvars['localhost']['oricacscid'] }}"
   tasks:
     - debug:
        msg: linuxSoeUri is {{ linuxSoeUri }}
     - name: Classify hosts depending on their OS distribution
       group_by:
         key: os_{{ ansible_facts['distribution'] }}
     - name: download azcopy
       become: true
       ansible.builtin.get_url:
         url:  "{{ azcopyUrl }}"
         dest: "/usr/bin/azcopy"
         mode: "0755"
     - name: download soe files via azcopy
       become: true
       ansible.builtin.shell: /usr/bin/azcopy copy --recursive --overwrite false "{{ linuxSoeUri }}" "{{ linuxSoePath }}"

 - hosts: os_Ubuntu
   gather_facts: True
   tasks:


    #copy zscaler, root ca, sub1 ca, sub2 ca and update CA store
      - name: Copy CA certificates to target hosts
        become: true
        ansible.builtin.copy:
          src:  "{{ linuxSoePath }}/soe/cert/" 
          dest: /usr/local/share/ca-certificates/
          remote_src: yes
      - name: Update CA trust store
        shell: "update-ca-certificates"
        become: true
    #configure ori.orica.net dns suffix
      - name: Install a list of packages
        become: true
        ansible.builtin.apt:
          pkg:
          - resolvconf
          state: present
      - name: add ori.orica.net suffix to resolv.conf
        become: true
        ansible.builtin.lineinfile:
          path: /etc/resolvconf/resolv.conf.d/tail
          line:  search ori.orica.net
          create: yes
      - name: update /etc/resolv.conf
        shell: "resolvconf -u"
        become: true

    #install and configure nxlog / point to 10.172.32.101
      - name: Install a list of packages
        become: true
        ansible.builtin.apt:
          pkg:
          - libapr1
          - libdbi1
          state: present
      - name: install nxlog deb package
        become: true
        ansible.builtin.apt: "{{ linuxSoePath }}/soe/linux/deb/nxlog-ce_*ubuntu22*.deb"
      #config goes here

    #install servicenow agent
      - name: install snowagent deb package
        become: true
        ansible.builtin.apt: "{{ linuxSoePath }}/soe/linux/deb/Orica-Linux-snowagent-7.0.0-x64.deb"
      - name: update snow configuration
        shell: "/opt/snow/snowcron -f /opt/snow/snowcron.conf /opt/snow/snowagent"
        become: true

    #install crowdstrike
      - name: install falcon deb package
        become: true
        ansible.builtin.apt: "{{ linuxSoePath }}/soe/linux/deb/falcon-sensor_7.06.0-16108_amd64.deb"
      - name: configure CID
        become: true
        shell: "/opt/CrowdStrike/falconctl -s -f --cid='{{ hostvars['localhost']['oricacscid'] }}'"
        when: ansible_facts.services['falcon-sensor.service'].state != 'running'
      - name: enable and start falcon-sensor
        ansible.builtin.systemd_service:
          state: started
          enabled: true
          name: falcon-sensor
        when: ansible_facts.services['falcon-sensor.service'].state != 'running'
    # #install qualys
    #   - name: install qualys deb package
    #     become: true
    #     ansible.builtin.apt: "{{ linuxSoePath }}/soe/linux/deb/QualysCloudAgent.deb"
    #   - name: configure qualys CID
    #     become: true
    #     shell: "/usr/local/qualys/cloud-agent/bin/qualys-cloud-agent.sh CustomerId='{{qualysCid}}' ActivationId='{{qualysActId}}' ServerUri='{{qualysUri}}'"
    #     when: ansible_facts.services['qualys-cloud-agent.service'].state != 'running'
    #   - name: enable and start falcon-sensor
    #     ansible.builtin.systemd_service:
    #       state: started
    #       enabled: true
    #       name: qualys
    #     when: ansible_facts.services['qualys-cloud-agent.service'].state != 'running'
    # #install servicenow acc
    #   - name: Install ServiceNow ACC via shell
    #     become: true
    #     shell: "ACC_API_KEY='{{accApiKey}}' ACC_MID='{{accMid}}' bash -c '$(curl -L https://orica2.service-now.com/api/sn_agent/agents/install_agent)'"
    #     when: ansible_facts.services['acc.service'].state != 'running'
    
    # #install illumio
    #   - name: Install Illumio via shell
    #     become: true
    #     shell: "rm -fr /opt/illumio_ven_data/tmp && umask 026 && mkdir -p /opt/illumio_ven_data/tmp && curl --tlsv1 'https://scp1.illum.io:443/api/v21/software/ven/image?pair_script=pair.sh&profile_id=1734' -o /opt/illumio_ven_data/tmp/pair.sh && chmod +x /opt/illumio_ven_data/tmp/pair.sh && /opt/illumio_ven_data/tmp/pair.sh --management-server scp1.illum.io:443 --activation-code '{{illumioAcode}}'"
    #     # when: ansible_facts.apt['illumio-ven-*.x86_64'].state != 'running'
    #   - name: enable and start illumio-ven
    #     ansible.builtin.systemd_service:
    #       state: started
    #       enabled: true
    #       name: illumio-ven
    #     when: ansible_facts.services['illumio-ven.service'].state != 'running'    
    #configure to allow Icinga

    #drop banner.txt, configure banner, PermitRootLogin no on /etc/ssh/sshd_config
      - name: Copy banner from soe directory
        become: true
        ansible.builtin.copy:
          src:  "{{ linuxSoePath }}/soe/linux/banner.txt" 
          dest: /etc/ssh/banner.txt
          remote_src: yes
      - name: Configure sshd_config with banner and PermitRootLogin
        ansible.builtin.lineinfile:
          path: /etc/ssh/sshd_config
          state: present
          regexp: '^#Banner none'
          line: 'Banner /etc/ssh/banner.txt'
      
    #configure AD login

    #configure tmux

    #configure zsh


