---

 - name: talk to all hosts just so we can learn about them
   hosts: dev
   tasks:
     - name: Classify hosts depending on their OS distribution
       group_by:
         key: os_{{ ansible_facts['distribution'] }}

 - hosts: os_Ubuntu
   gather_facts: False
   tasks:
    # copy soe folder
      - name: download required files and folders
        become: true
        ansible.builtin.get_url:
          url:  https://stshareddevaue01.blob.core.windows.net/soe?sp=r&st=2025-04-28T03:31:46Z&se=2028-04-28T11:31:46Z&spr=https&sv=2024-11-04&sr=c&sig=IkTerC2Y%2FC3Fi%2BRq2PFZUszbcneFofDrQvvLTOaqCbQ%3D
          dest: "{{ linuxSoePath }}"

    #copy zscaler, root ca, sub1 ca, sub2 ca and update CA store
      - name: Copy CA certificates to target hosts
        become: true
        ansible.builtin.copy:
          src:  "{{ linuxSoePath }}/cert/" 
          dest: /usr/local/share/ca-certificates/
      - name: Update CA trust store
        shell: "update-ca-certificates"
        become: true
    #configure ori.orica.net dns suffix
      - name: Install a list of packages
        become: true
        ansible.builtin.apt:
          pkg:
          - resolvconf
          state: present
      - name: add ori.orica.net suffix to resolv.conf
        become: true
        ansible.builtin.lineinfile:
          path: /etc/resolvconf/resolv.conf.d/tail
          line:  search ori.orica.net
          create: yes
      - name: update /etc/resolv.conf
        shell: "resolvconf -u"
        become: true

    #install and configure nxlog / point to 10.172.32.101
      - name: Install a list of packages
        become: true
        ansible.builtin.apt:
          pkg:
          - nxlog-ce
          - libapr1
          - libdbi1
          state: present
      #config goes here

    #install servicenow agent

    #install crowdstrike

    #install qualys

    #install servicenow acc

    #install illumio

    #configure to allow Icinga

    #drop banner.txt, configure banner, PermitRootLogin no on /etc/ssh/sshd_config
      - name: Copy banner from soe directory
        become: true
        ansible.builtin.copy:
          src:  "{{ linuxSoePath }}/linux/banner.txt" 
          dest: /etc/ssh/banner.txt
      - name: Configure sshd_config with banner and PermitRootLogin
        ansible.builtin.lineinfile:
          path: /etc/ssh/sshd_config
          state: present
          regexp: '^#Banner none'
          line: 'Banner /etc/ssh/banner.txt'
      
    #configure AD login

    #configure tmux

    #configure zsh


