---
- hosts: dev
  tasks: 

  - name: Set authorized keys taken from url
    ansible.posix.authorized_key:
      user: admin3
      state: present
      key: https://raw.githubusercontent.com/jcaldozo-orica/dev-ansible/refs/heads/main/common/ansible.key
  - name: create systemadmin group
    become: true
    shell: 'groupadd -g 650 systemadmin'
  - name: add systemadmin to sudo
    become: true
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/orica
      line:  '%systemadmin ALL = (ALL) NOPASSWD:ALL'
      create: yes
  - name: add admin3 to systemadmin
    become: true
    shell: 'usermod -aG systemadmin admin3'
    
