---
- hosts: dev
  tasks: 

  - name: Set authorized keys taken from url
    ansible.posix.authorized_key:
      user: admin3
      state: present
      key: https://raw.githubusercontent.com/jcaldozo-orica/dev-ansible/refs/heads/main/common/ansible.key