---

- name: control node to run keyvault retrieval
  hosts: localhost
  tasks:
    - include_tasks: get_kv_secrets.yml
      vars:
        secretName: "oricacscid"
      register: kvValue
    - name: declare falcon cid
      ansible.builtin.set_fact:
        oricacscid: "{{ kvValue }}"
    - name: Output key vault secret
      debug: 
        msg="oricacscid is {{ kvValue }}"