---
- name: TEST
  hosts: dev
  gather_facts: yes
  vars:
    install_servicenowagent: false
    install_crowdstrike: false
    install_qualys: false
    install_servicenowacc: false
    install_nxlog: false
    install_illumio: true
    install_icinga: false
    install_sccm: false
    joinOriDomain: false
    server_region: "apac" #apac/nala/emea
  tasks:
    - include_role: 
        name: soe