---
- name: TEST
  hosts: dev
  gather_facts: yes
  vars:
    install_crowdstrike: true
    install_qualys: false
    install_servicenowacc: false
    install_nxlog: false
    install_illumio: false
    install_icinga: false
    joinOriDomain: false
  tasks:
    - include_role: 
        name: soe