---
- name: TEST
  hosts: dev
  gather_facts: yes
  vars:
    install_servicenowagent: false
    install_crowdstrike: false
    install_qualys: true
    install_servicenowacc: true
    install_nxlog: true
    install_illumio: true
    install_icinga: true
    joinOriDomain: true
  tasks:
    - include_role: 
        name: soe