---
- name: TEST
  hosts: dev
  gather_facts: yes
  vars:
    install_common: true
    install_servicenowagent: true
    install_crowdstrike: true
    install_qualys: true
    install_servicenowacc: true
    install_nxlog: true
    install_illumio: true
    install_icinga: true
    install_sccm: true
    joinOriDomain: true
    server_region: "apac" #apac/nala/emea
  tasks:
    - include_role: 
        name: soe