---
- name: TEST
  hosts: dev
  become: true
  gather_facts: yes
  vars:
    install_crowdstrike: true
    install_qualys: true
    install_servicenowacc: true
    install_nxlog: true
    install_illumio: true
    install_icinga: false
    joinOriDomain: false
  tasks:
    - include_role: 
        name: soe