---
- hosts: dev
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_port: 5985
    ansible_winrm_server_cert_validation: ignore
  tasks:
  - name: Create directory structure
    ansible.windows.win_file:
      path: C:\oricatools
      state: directory
  - name: Download ConfigureRemotingForAnsible.ps1
    ansible.windows.win_get_url:
      url: https://github.com/jcaldozo-orica/dev-ansible/raw/refs/heads/main/roles/soe/files/ConfigureRemotingForAnsible.ps1
      dest: c:\oricatools\ConfigureRemotingForAnsible.ps1
      validate_certs: no
  - name: Run a command under PowerShell
    win_shell: c:\oricatools\ConfigureRemotingForAnsible.ps1